/******************************************************************************************
 * This code was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

import "github.com/mgenware/mingru-go-lib"

// TableTypeDept ...
type TableTypeDept struct {
}

// Dept ...
var Dept = &TableTypeDept{}

// ------------ Actions ------------

// DeptTableSelectPageResult ...
type DeptTableSelectPageResult struct {
	ID   string
	Name string
}

// SelectPage ...
func (da *TableTypeDept) SelectPage(queryable mingru.Queryable, page int, pageSize int) ([]*DeptTableSelectPageResult, bool, error) {
	limit := pageSize + 1
	offset := (page - 1) * pageSize
	max := pageSize
	rows, err := queryable.Query("SELECT `dept_no`, `dept_name` FROM `departments` ORDER BY `dept_no` LIMIT ? OFFSET ?", limit, offset)
	if err != nil {
		return nil, false, err
	}
	result := make([]*DeptTableSelectPageResult, 0, limit)
	itemCounter := 0
	defer rows.Close()
	for rows.Next() {
		itemCounter++
		if itemCounter <= max {
			item := &DeptTableSelectPageResult{}
			err = rows.Scan(&item.ID, &item.Name)
			if err != nil {
				return nil, false, err
			}
			result = append(result, item)
		}
	}
	err = rows.Err()
	if err != nil {
		return nil, false, err
	}
	return result, itemCounter > len(result), nil
}
