/******************************************************************************************
 * This file was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

import (
	"fmt"

	"github.com/mgenware/mingru-go-lib"
)

type DeptTAAGType struct {
}

var DeptTA = &DeptTAAGType{}

// ------------ Actions ------------

type DeptTAAGSelectPageResult struct {
	ID   string
	Name string
}

func (mrTable *DeptTAAGType) SelectPage(mrQueryable mingru.Queryable, page int, pageSize int) ([]DeptTAAGSelectPageResult, bool, error) {
	if page <= 0 {
		err := fmt.Errorf("Invalid page %v", page)
		return nil, false, err
	}
	if pageSize <= 0 {
		err := fmt.Errorf("Invalid page size %v", pageSize)
		return nil, false, err
	}
	limit := pageSize + 1
	offset := (page - 1) * pageSize
	max := pageSize
	rows, err := mrQueryable.Query("SELECT `dept_no`, `dept_name` FROM `departments` ORDER BY `dept_no` LIMIT ? OFFSET ?", limit, offset)
	if err != nil {
		return nil, false, err
	}
	result := make([]DeptTAAGSelectPageResult, 0, limit)
	itemCounter := 0
	defer rows.Close()
	for rows.Next() {
		itemCounter++
		if itemCounter <= max {
			var item DeptTAAGSelectPageResult
			err = rows.Scan(&item.ID, &item.Name)
			if err != nil {
				return nil, false, err
			}
			result = append(result, item)
		}
	}
	err = rows.Err()
	if err != nil {
		return nil, false, err
	}
	return result, itemCounter > len(result), nil
}
