 /******************************************************************************************
 * This code was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

import (
	"time"

	"github.com/mgenware/go-packagex/v5/dbx"
)

// TableTypeEmployee ...
type TableTypeEmployee struct {
}

// Employee ...
var Employee = &TableTypeEmployee{}

// ------------ Actions ------------

// DeleteAll ...
func (da *TableTypeEmployee) DeleteAll(queryable dbx.Queryable) (int, error) {
	result, err := queryable.Exec("DELETE FROM `employees`")
	return dbx.GetRowsAffectedIntWithError(result, err)
}

// DeleteByBirthDate ...
func (da *TableTypeEmployee) DeleteByBirthDate(queryable dbx.Queryable, birthDate time.Time) (int, error) {
	result, err := queryable.Exec("DELETE FROM `employees` WHERE `birth_date` = ?", birthDate)
	return dbx.GetRowsAffectedIntWithError(result, err)
}

// DeleteByID ...
func (da *TableTypeEmployee) DeleteByID(queryable dbx.Queryable, id int) error {
	result, err := queryable.Exec("DELETE FROM `employees` WHERE `emp_no` = ?", id)
	return dbx.CheckOneRowAffectedWithError(result, err)
}

// InsertUser ...
func (da *TableTypeEmployee) InsertUser(queryable dbx.Queryable, id int, firstName string, lastName string, gender string, birthDate time.Time, hireDate time.Time) (uint64, error) {
	result, err := queryable.Exec("INSERT INTO `employees` (`emp_no`, `first_name`, `last_name`, `gender`, `birth_date`, `hire_date`) VALUES (?, ?, ?, ?, ?, ?)", id, firstName, lastName, gender, birthDate, hireDate)
	return dbx.GetLastInsertIDUint64WithError(result, err)
}

// EmployeeTableSelectAllResult ...
type EmployeeTableSelectAllResult struct {
	ID        int
	FirstName string
	LastName  string
	Gender    string
	BirthDate time.Time
	HireDate  time.Time
}

// SelectAll ...
func (da *TableTypeEmployee) SelectAll(queryable dbx.Queryable) ([]*EmployeeTableSelectAllResult, error) {
	rows, err := queryable.Query("SELECT `emp_no`, `first_name`, `last_name`, `gender`, `birth_date`, `hire_date` FROM `employees`")
	if err != nil {
		return nil, err
	}
	result := make([]*EmployeeTableSelectAllResult, 0)
	defer rows.Close()
	for rows.Next() {
		item := &EmployeeTableSelectAllResult{}
		err = rows.Scan(&item.ID, &item.FirstName, &item.LastName, &item.Gender, &item.BirthDate, &item.HireDate)
		if err != nil {
			return nil, err
		}
		result = append(result, item)
	}
	err = rows.Err()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// EmployeeTableSelectByIDResult ...
type EmployeeTableSelectByIDResult struct {
	ID        int
	FirstName string
	LastName  string
	Gender    string
	BirthDate time.Time
	HireDate  time.Time
}

// SelectByID ...
func (da *TableTypeEmployee) SelectByID(queryable dbx.Queryable, id int) (*EmployeeTableSelectByIDResult, error) {
	result := &EmployeeTableSelectByIDResult{}
	err := queryable.QueryRow("SELECT `emp_no`, `first_name`, `last_name`, `gender`, `birth_date`, `hire_date` FROM `employees` WHERE `emp_no` = ?", id).Scan(&result.ID, &result.FirstName, &result.LastName, &result.Gender, &result.BirthDate, &result.HireDate)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// SelectSig ...
func (da *TableTypeEmployee) SelectSig(queryable dbx.Queryable, id int) (time.Time, error) {
	var result time.Time
	err := queryable.QueryRow("SELECT `birth_date` FROM `employees` WHERE `emp_no` = ?", id).Scan(&result)
	if err != nil {
		return result, err
	}
	return result, nil
}

// UpdateName ...
func (da *TableTypeEmployee) UpdateName(queryable dbx.Queryable, id int, firstName string, lastName string) error {
	result, err := queryable.Exec("UPDATE `employees` SET `first_name` = ?, `last_name` = ? WHERE `emp_no` = ?", firstName, lastName, id)
	return dbx.CheckOneRowAffectedWithError(result, err)
}
