/******************************************************************************************
 * This file was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

CREATE TABLE `departments` (
	`dept_no` CHAR(4) NOT NULL,
	`dept_name` VARCHAR(40) NOT NULL,
	PRIMARY KEY (`dept_no`)
)
CHARACTER SET=utf8mb4
COLLATE=utf8mb4_unicode_ci
;
